import Head from "next/head";
import { ItemCard } from "~/components/ItemCard";
import { api } from "~/utils/api";

export default function Browse() {
    const getListings = api.listings.list.useQuery();

    return (
        <>
            <Head>
                <title>Waiheke Place</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col bg-gray-800 gap-12">
                <h1 className="mt-12 pl-4 text-4xl">Browse Items</h1>
                <div className="container grid grid-cols-3 items-center justify-center gap-4">
                    {getListings?.data?.map(item => <ItemCard key={item.id} listing={item} />)}
                </div>
            </main>
        </>
    );
}
