import Head from "next/head";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/clerk-react";
import { NavBar } from "~/components/NavBar";

export default function Home() {

  const user = useUser();

  return (
    <>
      <Head>
        <title>Waiheke Place</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      </main>
    </>
  );
}
