import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Waiheke Place</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-800">
      </main>
    </>
  );
}
